// data source

const movieData = [
    { title: 'The Shawshank Redemption (1994)' },
    { title: 'The Godfather (1972)' },
    { title: 'The Dark Knight (2008)' },
    { title: 'The Godfather: Part II (1974)' },
    { title: 'The Lord of the Rings: The Return of the King (2003)' },
    { title: 'Pulp Fiction (1994)' },
    { title: "Schindler's List (1993)" },
    { title: '12 Angry Men (1957)' },
    { title: 'Inception (2010)' },
    { title: 'Fight Club (1999)' },
    { title: 'The Lord of the Rings: The Fellowship of the Ring (2001)' },
    { title: 'Forrest Gump (1994)' },
    { title: 'The Good, the Bad and the Ugly (1966)' },
    { title: 'Hamilton (2020)' },
    { title: 'The Lord of the Rings: The Two Towers (2002)' },
    { title: 'The Matrix (1999)' },
    { title: 'Goodfellas (1990)' },
    { title: 'Star Wars: Episode V - The Empire Strikes Back (1980)' },
    { title: "One Flew Over the Cuckoo's Nest (1975)" },
    { title: 'Parasite (2019)' },
    { title: 'Interstellar (2014)' },
    { title: 'City of God (2002)' },
    { title: 'Spirited Away (2001)' },
    { title: 'Saving Private Ryan (1998)' },
    { title: 'The Green Mile (1999)' },
    { title: 'Life Is Beautiful (1997)' },
    { title: 'Se7en (1995)' },
    { title: 'The Silence of the Lambs (1991)' },
    { title: 'Star Wars: Episode IV - A New Hope (1977)' },
    { title: 'Harakiri (1962)' },
    { title: 'Seven Samurai (1954)' },
    { title: "It's a Wonderful Life (1946)" },
    { title: 'Joker (2019)' },
    { title: 'Whiplash (2014)' },
    { title: 'The Intouchables (2011)' },
    { title: 'The Prestige (2006)' },
    { title: 'The Departed (2006)' },
    { title: 'The Pianist (2002)' },
    { title: 'Gladiator (2000)' },
    { title: 'American History X (1998)' },
    { title: 'The Usual Suspects (1995)' },
    { title: 'Léon: The Professional (1994)' },
    { title: 'The Lion King (1994)' },
    { title: 'Terminator 2: Judgment Day (1991)' },
    { title: 'Cinema Paradiso (1988)' },
    { title: 'Grave of the Fireflies (1988)' },
    { title: 'Back to the Future (1985)' },
    { title: 'Anand (1971)' },
    { title: 'Once Upon a Time in the West (1968)' },
    { title: 'Psycho (1960)' },
    { title: 'Casablanca (1942)' },
    { title: 'Modern Times (1936)' },
    { title: 'City Lights (1931)' },
    { title: 'Capernaum (2018)' },
    { title: 'Ayla: The Daughter of War (2017)' },
    { title: 'Your Name. (2016)' },
    { title: 'Dangal (2016)' },
    { title: 'Spider-Man: Into the Spider-Verse (2018)' },
    { title: 'Avengers: Endgame (2019)' },
    { title: 'Avengers: Infinity War (2018)' },
    { title: 'Coco (I) (2017)' },
    { title: 'Django Unchained (2012)' },
    { title: 'The Dark Knight Rises (2012)' },
    { title: '3 Idiots (2009)' },
    { title: 'Like Stars on Earth (2007)' },
    { title: 'WALL·E (2008)' },
    { title: 'The Lives of Others (2006)' },
    { title: 'Oldboy (2003)' },
    { title: 'Memento (2000)' },
    { title: 'Princess Mononoke (1997)' },
    { title: 'Once Upon a Time in America (1984)' },
    { title: 'Raiders of the Lost Ark (1981)' },
    { title: 'The Shining (1980)' },
    { title: 'Apocalypse Now (1979)' },
    { title: 'Alien (1979)' },
    { title: 'High and Low (1963)' },
    {
      title: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)'
    },
    { title: 'Witness for the Prosecution (1957)' },
    { title: 'Paths of Glory (1957)' },
    { title: 'Rear Window (1954)' },
    { title: 'Sunset Blvd. (1950)' },
    { title: 'The Great Dictator (1940)' },
    { title: '1917 (2019)' },
    { title: 'Uri: The Surgical Strike (2019)' },
    { title: 'Tumbbad (2018)' },
    { title: 'Andhadhun (2018)' },
    { title: 'Drishyam (2013)' },
    { title: 'The Hunt (2012)' },
    { title: 'A Separation (2011)' },
    { title: 'Incendies (2010)' },
    { title: '7 Kogustaki Mucize (2019)' },
    { title: 'My Father and My Son (2005)' },
    { title: 'Toy Story 3 (2010)' },
    { title: 'Inglourious Basterds (2009)' },
    { title: 'Eternal Sunshine of the Spotless Mind (2004)' },
    { title: 'Amélie (2001)' },
    { title: 'Snatch (2000)' },
    { title: 'Requiem for a Dream (2000)' },
    { title: 'American Beauty (1999)' },
    { title: 'Good Will Hunting (1997)' },
    { title: 'Children of Heaven (1997)' },
    { title: 'Toy Story (1995)' },
    { title: 'Braveheart (1995)' },
    { title: 'Reservoir Dogs (1992)' },
    { title: 'Full Metal Jacket (1987)' },
    { title: 'Come and See (1985)' },
    { title: 'Aliens (1986)' },
    { title: 'Amadeus (1984)' },
    { title: 'Scarface (1983)' },
    { title: 'Star Wars: Episode VI - Return of the Jedi (1983)' },
    { title: 'Das Boot (1981)' },
    { title: 'Taxi Driver (1976)' },
    { title: 'The Sting (1973)' },
    { title: 'A Clockwork Orange (1971)' },
    { title: '2001: A Space Odyssey (1968)' },
    { title: 'For a Few Dollars More (1965)' },
    { title: 'Lawrence of Arabia (1962)' },
    { title: 'The Apartment (1960)' },
    { title: 'North by Northwest (1959)' },
    { title: 'Vertigo (1958)' },
    { title: "Singin' in the Rain (1952)" },
    { title: 'Ikiru (1952)' },
    { title: 'Bicycle Thieves (1948)' },
    { title: 'Double Indemnity (1944)' },
    { title: 'Citizen Kane (1941)' },
    { title: 'M (1931)' },
    { title: 'Metropolis (1927)' },
    { title: 'The Kid (1921)' },
    { title: 'Chhichhore (2019)' },
    { title: 'K.G.F: Chapter 1 (2018)' },
    { title: 'Green Book (2018)' },
    { title: 'Three Billboards Outside Ebbing, Missouri (2017)' },
    { title: 'Talvar (2015)' },
    { title: 'Baahubali 2: The Conclusion (2017)' },
    { title: 'Klaus (2019)' },
    { title: 'Drishyam (2015)' },
    { title: 'Queen (2013)' },
    { title: 'Tangerines (2013)' },
    { title: 'Bhaag Milkha Bhaag (2013)' },
    { title: 'Gangs of Wasseypur (2012)' },
    { title: 'Udaan (2010)' },
    { title: 'Paan Singh Tomar (2012)' },
    { title: 'The Secret in Their Eyes (2009)' },
    { title: 'Warrior (2011)' },
    { title: 'Shutter Island (2010)' },
    { title: 'Up (2009)' },
    { title: 'The Wolf of Wall Street (2013)' },
    { title: 'Chak De! India (2007)' },
    { title: 'There Will Be Blood (2007)' },
    { title: "Pan's Labyrinth (2006)" },
    { title: 'V for Vendetta (2005)' },
    { title: 'Rang De Basanti (2006)' },
    { title: 'Black (2005)' },
    { title: 'Batman Begins (2005)' },
    { title: 'Swades (2004)' },
    { title: 'Downfall (2004)' },
    { title: "Howl's Moving Castle (2004)" },
    { title: 'A Beautiful Mind (2001)' },
    { title: 'Hera Pheri (2000)' },
    { title: 'Lock, Stock and Two Smoking Barrels (1998)' },
    { title: 'L.A. Confidential (1997)' },
    { title: 'The Bandit (1996)' },
    { title: 'Heat (1995)' },
    { title: 'Casino (1995)' },
    { title: 'Andaz Apna Apna (1994)' },
    { title: 'Unforgiven (1992)' },
    { title: 'Indiana Jones and the Last Crusade (1989)' },
    { title: 'My Neighbor Totoro (1988)' },
    { title: 'Die Hard (1988)' },
    { title: 'Ran (1985)' },
    { title: 'Raging Bull (1980)' },
    { title: 'Stalker (1979)' },
    { title: 'The Message (1976)' },
    { title: 'Sholay (1975)' },
    { title: 'Monty Python and the Holy Grail (1975)' },
    { title: 'The Great Escape (1963)' },
    { title: 'To Kill a Mockingbird (1962)' },
    { title: 'Yojimbo (1961)' },
    { title: 'Judgment at Nuremberg (1961)' },
    { title: 'Some Like It Hot (1959)' },
    { title: 'Wild Strawberries (1957)' },
    { title: 'The Seventh Seal (1957)' },
    { title: 'Rififi (1955)' },
    { title: 'Dial M for Murder (1954)' },
    { title: 'Tokyo Story (1953)' },
    { title: 'Rashomon (1950)' },
    { title: 'All About Eve (1950)' },
    { title: 'The Treasure of the Sierra Madre (1948)' },
    { title: 'To Be or Not to Be (1942)' },
    { title: 'The Gold Rush (1925)' },
    { title: 'Sherlock Jr. (1924)' },
    { title: 'Portrait of a Lady on Fire (2019)' },
    { title: 'Pink (III) (2016)' },
    { title: 'A Silent Voice: The Movie (2016)' },
    { title: 'The Invisible Guest (2016)' },
    { title: 'The Handmaiden (2016)' },
    { title: 'Mommy (I) (2014)' },
    { title: 'Haider (2014)' },
    { title: 'Wild Tales (2014)' },
    { title: 'Winter Sleep (2014)' },
    { title: 'Baahubali: The Beginning (2015)' },
    { title: 'Gully Boy (2019)' },
    { title: 'PK (2014)' },
    { title: 'OMG: Oh My God! (2012)' },
    { title: 'The Grand Budapest Hotel (2014)' },
    { title: 'Gone Girl (2014)' },
    { title: 'Wolf Children (2012)' },
    { title: 'Hacksaw Ridge (2016)' },
    { title: 'Inside Out (I) (2015)' },
    { title: 'Barfi! (2012)' },
    { title: '12 Years a Slave (2013)' },
    { title: 'Rush (I) (2013)' },
    { title: 'Ford v Ferrari (2019)' },
    { title: 'Spotlight (I) (2015)' },
    { title: 'Song of the Sea (2014)' },
    { title: 'Kahaani (2012)' },
    { title: 'Zindagi Na Milegi Dobara (2011)' },
    { title: 'Prisoners (2013)' },
    { title: 'Mad Max: Fury Road (2015)' },
    { title: 'A Wednesday (2008)' },
    { title: 'Gran Torino (2008)' },
    { title: 'Harry Potter and the Deathly Hallows: Part 2 (2011)' },
    { title: 'Departures (2008)' },
    { title: "Hachi: A Dog's Tale (2009)" },
    { title: 'Mary and Max (2009)' },
    { title: 'How to Train Your Dragon (2010)' },
    { title: 'Elite Squad (2007)' },
    { title: 'Into the Wild (2007)' },
    { title: 'No Country for Old Men (2007)' },
    { title: 'Lage Raho Munna Bhai (2006)' },
    { title: 'Million Dollar Baby (2004)' },
    { title: 'Hotel Rwanda (2004)' },
    { title: 'Tae Guk Gi: The Brotherhood of War (2004)' },
    { title: 'Before Sunset (2004)' },
    { title: 'Munna Bhai M.B.B.S. (2003)' },
    { title: 'Memories of Murder (2003)' },
    { title: 'Dil Chahta Hai (2001)' },
    { title: 'Kill Bill: Vol. 1 (2003)' },
    { title: 'Finding Nemo (2003)' },
    { title: 'Catch Me If You Can (2002)' },
    { title: 'Amores Perros (2000)' },
    { title: 'Neon Genesis Evangelion: The End of Evangelion (1997)' },
    { title: 'Lagaan: Once Upon a Time in India (2001)' },
    { title: 'The Sixth Sense (1999)' },
    { title: 'The Legend of 1900 (1998)' },
    { title: 'The Truman Show (1998)' },
    { title: 'Black Cat, White Cat (1998)' },
    { title: 'The Big Lebowski (1998)' },
    { title: 'In the Mood for Love (2000)' },
    { title: 'Trainspotting (1996)' },
    { title: 'Fargo (1996)' },
    { title: 'Underground (1995)' },
    { title: 'La Haine (1995)' },
    { title: 'Dilwale Dulhania Le Jayenge (1995)' },
    { title: 'Before Sunrise (1995)' },
    { title: 'Three Colors: Red (1994)' },
    { title: 'Chungking Express (1994)' },
    { title: 'Jurassic Park (1993)' },
    { title: 'In the Name of the Father (1993)' },
    { title: 'Raise the Red Lantern (1991)' },
    { title: 'Dead Poets Society (1989)' },
    { title: 'The Princess Bride (1987)' },
    { title: 'Stand by Me (1986)' },
    { title: 'Platoon (1986)' },
    { title: 'Paris, Texas (1984)' },
    { title: 'Nausicaä of the Valley of the Wind (1984)' },
    { title: 'The Thing (1982)' },
    { title: 'Pink Floyd: The Wall (1982)' },
    { title: 'Fitzcarraldo (1982)' },
    { title: 'Fanny and Alexander (1982)' },
    { title: 'Blade Runner (1982)' },
    { title: 'The Elephant Man (1980)' },
    { title: "Monty Python's Life of Brian (1979)" },
    { title: 'The Deer Hunter (1978)' },
    { title: 'Rocky (1976)' },
    { title: 'Network (1976)' },
    { title: 'Barry Lyndon (1975)' },
    { title: 'The Mirror (1975)' },
    { title: 'Chinatown (1974)' },
    { title: 'Paper Moon (1973)' },
    { title: 'Cries & Whispers (1972)' },
    { title: 'Solaris (1972)' },
    { title: 'Le Samouraï (1967)' },
    { title: 'Cool Hand Luke (1967)' },
    { title: 'Persona (1966)' },
    { title: 'Andrei Rublev (1966)' },
    { title: 'The Battle of Algiers (1966)' },
    { title: 'The Exterminating Angel (1962)' },
    { title: 'What Ever Happened to Baby Jane? (1962)' },
    { title: 'Sanjuro (1962)' },
    { title: 'The Man Who Shot Liberty Valance (1962)' },
    { title: "Ivan's Childhood (1962)" },
    { title: 'The Virgin Spring (1960)' },
    { title: 'Inherit the Wind (1960)' },
    { title: 'The 400 Blows (1959)' },
    { title: 'Ben-Hur (1959)' },
    { title: 'The Hidden Fortress (1958)' },
    { title: 'Sweet Smell of Success (1957)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' },
    { title: 'The Bridge on the River Kwai (1957)' },
    { title: 'On the Waterfront (1954)' },
    { title: 'The Wages of Fear (1953)' },
    { title: 'Ace in the Hole (1951)' },
    { title: 'White Heat (1949)' },
    { title: 'The Third Man (1949)' },
    { title: 'The Red Shoes (1948)' },
    { title: 'The Shop Around the Corner (1940)' },
    { title: 'Rebecca (1940)' },
    { title: 'Mr. Smith Goes to Washington (1939)' },
    { title: 'Gone with the Wind (1939)' },
    { title: 'La Grande Illusion (1937)' },
    { title: 'It Happened One Night (1934)' },
    { title: 'The Passion of Joan of Arc (1928)' },
    { title: 'The Circus (1928)' },
    { title: 'Sunrise (1927)' },
    { title: 'The General (1926)' },
    { title: 'The Cabinet of Dr. Caligari (1920)' },
    { title: 'Shoplifters (2018)' },
    { title: 'Badhaai Ho (2018)' },
    { title: 'Marriage Story (2019)' },
    { title: 'Togo (2019)' },
    { title: 'Airlift (2016)' },
    { title: 'Bajrangi Bhaijaan (2015)' },
    { title: 'Baby (I) (2015)' },
    { title: 'La La Land (2016)' },
    { title: 'Lion (2016)' },
    { title: 'The Martian (2015)' },
    { title: 'Zootopia (2016)' },
    { title: 'The Tale of The Princess Kaguya (2013)' },
    { title: 'Wonder (I) (2017)' },
    { title: 'Special 26 (2013)' },
    { title: 'Short Term 12 (2013)' },
    { title: 'The Raid 2 (2014)' },
    { title: 'The Imitation Game (2014)' },
    { title: 'Guardians of the Galaxy (2014)' },
    { title: 'Blade Runner 2049 (2017)' },
    { title: 'Her (2013)' },
    { title: 'Bohemian Rhapsody (2018)' },
    { title: 'The Revenant (2015)' },
    { title: 'The Perks of Being a Wallflower (2012)' },
    { title: 'Elite Squad 2: The Enemy Within (2010)' },
    { title: "The King's Speech (2010)" },
    { title: 'The Help (2011)' },
    { title: 'Deadpool (2016)' },
    { title: 'Darbareye Elly (2009)' },
    { title: 'Dev.D (2009)' },
    { title: 'Ip Man (2008)' },
    { title: 'My Name Is Khan (2010)' },
    { title: 'The Breath (2009)' },
    { title: 'Slumdog Millionaire (2008)' },
    { title: 'Black Swan (2010)' },
    { title: 'The Avengers (2012)' },
    { title: 'Persepolis (2007)' },
    { title: 'Dallas Buyers Club (2013)' },
    { title: 'The Pursuit of Happyness (2006)' },
    { title: 'Blood Diamond (2006)' },
    { title: 'The Bourne Ultimatum (2007)' },
    { title: '3-Iron (2004)' },
    { title: 'Sin City (2005)' },
    { title: 'The Diving Bell and the Butterfly (2007)' },
    { title: 'G.O.R.A. (2004)' },
    { title: 'Ratatouille (2007)' },
    { title: 'Casino Royale (2006)' },
    { title: 'Kill Bill: Vol. 2 (2004)' },
    { title: 'The Return (2003)' },
    { title: 'Spring, Summer, Fall, Winter... and Spring (2003)' },
    { title: 'The Sea Inside (I) (2004)' },
    { title: 'Cinderella Man (2005)' },
    { title: 'Kal ho naa ho (2003)' },
    { title: 'Infernal Affairs (2002)' },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    },
    { title: 'Big Fish (2003)' },
    { title: 'The Incredibles (2004)' },
    { title: 'My Sassy Girl (2001)' },
    { title: 'Dogville (2003)' },
    { title: 'Vizontele (2001)' },
    { title: 'Donnie Darko (2001)' },
    { title: 'Monsters, Inc. (2001)' },
    { title: 'Magnolia (1999)' },
    { title: 'Dancer in the Dark (2000)' },
    { title: 'Mulholland Drive (2001)' },
    { title: 'The Straight Story (1999)' },
    { title: 'Perfect Blue (1997)' },
    { title: 'The Celebration (1998)' },
    { title: 'Central Station (1998)' },
    { title: 'The Iron Giant (1999)' },
    { title: "Knockin' on Heaven's Door (1997)" },
    { title: 'Sling Blade (1996)' },
    { title: 'Secrets & Lies (1996)' },
    { title: '12 Monkeys (1995)' },
    { title: 'Ghost in the Shell (1995)' },
    { title: 'The Nightmare Before Christmas (1993)' },
    { title: 'Groundhog Day (1993)' },
    { title: 'Blood In, Blood Out (1993)' },
    { title: 'Scent of a Woman (1992)' },
    { title: 'Aladdin (1992)' },
    { title: 'JFK (1991)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' },
    { title: 'The Bridge on the River Kwai (1957)' },
    { title: 'On the Waterfront (1954)' },
    { title: 'The Wages of Fear (1953)' },
    { title: 'Ace in the Hole (1951)' },
    { title: 'White Heat (1949)' },
    { title: 'The Third Man (1949)' },
    { title: 'The Red Shoes (1948)' },
    { title: 'The Shop Around the Corner (1940)' },
    { title: 'Rebecca (1940)' },
    { title: 'Mr. Smith Goes to Washington (1939)' },
    { title: 'Gone with the Wind (1939)' },
    { title: 'La Grande Illusion (1937)' },
    { title: 'It Happened One Night (1934)' },
    { title: 'The Passion of Joan of Arc (1928)' },
    { title: 'The Circus (1928)' },
    { title: 'Sunrise (1927)' },
    { title: 'The General (1926)' },
    { title: 'The Cabinet of Dr. Caligari (1920)' },
    { title: 'Shoplifters (2018)' },
    { title: 'Badhaai Ho (2018)' },
    { title: 'Marriage Story (2019)' },
    { title: 'Togo (2019)' },
    { title: 'Airlift (2016)' },
    { title: 'Bajrangi Bhaijaan (2015)' },
    { title: 'Baby (I) (2015)' },
    { title: 'La La Land (2016)' },
    { title: 'Lion (2016)' },
    { title: 'The Martian (2015)' },
    { title: 'Zootopia (2016)' },
    { title: 'The Tale of The Princess Kaguya (2013)' },
    { title: 'Wonder (I) (2017)' },
    { title: 'Special 26 (2013)' },
    { title: 'Short Term 12 (2013)' },
    { title: 'The Raid 2 (2014)' },
    { title: 'The Imitation Game (2014)' },
    { title: 'Guardians of the Galaxy (2014)' },
    { title: 'Blade Runner 2049 (2017)' },
    { title: 'Her (2013)' },
    { title: 'Bohemian Rhapsody (2018)' },
    { title: 'The Revenant (2015)' },
    { title: 'The Perks of Being a Wallflower (2012)' },
    { title: 'Elite Squad 2: The Enemy Within (2010)' },
    { title: "The King's Speech (2010)" },
    { title: 'The Help (2011)' },
    { title: 'Deadpool (2016)' },
    { title: 'Darbareye Elly (2009)' },
    { title: 'Dev.D (2009)' },
    { title: 'Ip Man (2008)' },
    { title: 'My Name Is Khan (2010)' },
    { title: 'The Breath (2009)' },
    { title: 'Slumdog Millionaire (2008)' },
    { title: 'Black Swan (2010)' },
    { title: 'The Avengers (2012)' },
    { title: 'Persepolis (2007)' },
    { title: 'Dallas Buyers Club (2013)' },
    { title: 'The Pursuit of Happyness (2006)' },
    { title: 'Blood Diamond (2006)' },
    { title: 'The Bourne Ultimatum (2007)' },
    { title: '3-Iron (2004)' },
    { title: 'Sin City (2005)' },
    { title: 'The Diving Bell and the Butterfly (2007)' },
    { title: 'G.O.R.A. (2004)' },
    { title: 'Ratatouille (2007)' },
    { title: 'Casino Royale (2006)' },
    { title: 'Kill Bill: Vol. 2 (2004)' },
    { title: 'The Return (2003)' },
    { title: 'Spring, Summer, Fall, Winter... and Spring (2003)' },
    { title: 'The Sea Inside (I) (2004)' },
    { title: 'Cinderella Man (2005)' },
    { title: 'Kal ho naa ho (2003)' },
    { title: 'Infernal Affairs (2002)' },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    },
    { title: 'Big Fish (2003)' },
    { title: 'The Incredibles (2004)' },
    { title: 'My Sassy Girl (2001)' },
    { title: 'Dogville (2003)' },
    { title: 'Vizontele (2001)' },
    { title: 'Donnie Darko (2001)' },
    { title: 'Monsters, Inc. (2001)' },
    { title: 'Magnolia (1999)' },
    { title: 'Dancer in the Dark (2000)' },
    { title: 'Mulholland Drive (2001)' },
    { title: 'The Straight Story (1999)' },
    { title: 'Perfect Blue (1997)' },
    { title: 'The Celebration (1998)' },
    { title: 'Central Station (1998)' },
    { title: 'The Iron Giant (1999)' },
    { title: "Knockin' on Heaven's Door (1997)" },
    { title: 'Sling Blade (1996)' },
    { title: 'Secrets & Lies (1996)' },
    { title: '12 Monkeys (1995)' },
    { title: 'Ghost in the Shell (1995)' },
    { title: 'The Nightmare Before Christmas (1993)' },
    { title: 'Groundhog Day (1993)' },
    { title: 'Blood In, Blood Out (1993)' },
    { title: 'Scent of a Woman (1992)' },
    { title: 'Aladdin (1992)' },
    { title: 'JFK (1991)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' },
    { title: 'The Bridge on the River Kwai (1957)' },
    { title: 'On the Waterfront (1954)' },
    { title: 'The Wages of Fear (1953)' },
    { title: 'Ace in the Hole (1951)' },
    { title: 'White Heat (1949)' },
    { title: 'The Third Man (1949)' },
    { title: 'The Red Shoes (1948)' },
    { title: 'The Shop Around the Corner (1940)' },
    { title: 'Rebecca (1940)' },
    { title: 'Mr. Smith Goes to Washington (1939)' },
    { title: 'Gone with the Wind (1939)' },
    { title: 'La Grande Illusion (1937)' },
    { title: 'It Happened One Night (1934)' },
    { title: 'The Passion of Joan of Arc (1928)' },
    { title: 'The Circus (1928)' },
    { title: 'Sunrise (1927)' },
    { title: 'The General (1926)' },
    { title: 'The Cabinet of Dr. Caligari (1920)' },
    { title: 'Shoplifters (2018)' },
    { title: 'Badhaai Ho (2018)' },
    { title: 'Marriage Story (2019)' },
    { title: 'Togo (2019)' },
    { title: 'Airlift (2016)' },
    { title: 'Bajrangi Bhaijaan (2015)' },
    { title: 'Baby (I) (2015)' },
    { title: 'La La Land (2016)' },
    { title: 'Lion (2016)' },
    { title: 'The Martian (2015)' },
    { title: 'Zootopia (2016)' },
    { title: 'The Tale of The Princess Kaguya (2013)' },
    { title: 'Wonder (I) (2017)' },
    { title: 'Special 26 (2013)' },
    { title: 'Short Term 12 (2013)' },
    { title: 'The Raid 2 (2014)' },
    { title: 'The Imitation Game (2014)' },
    { title: 'Guardians of the Galaxy (2014)' },
    { title: 'Blade Runner 2049 (2017)' },
    { title: 'Her (2013)' },
    { title: 'Bohemian Rhapsody (2018)' },
    { title: 'The Revenant (2015)' },
    { title: 'The Perks of Being a Wallflower (2012)' },
    { title: 'Elite Squad 2: The Enemy Within (2010)' },
    { title: "The King's Speech (2010)" },
    { title: 'The Help (2011)' },
    { title: 'Deadpool (2016)' },
    { title: 'Darbareye Elly (2009)' },
    { title: 'Dev.D (2009)' },
    { title: 'Ip Man (2008)' },
    { title: 'My Name Is Khan (2010)' },
    { title: 'The Breath (2009)' },
    { title: 'Slumdog Millionaire (2008)' },
    { title: 'Black Swan (2010)' },
    { title: 'The Avengers (2012)' },
    { title: 'Persepolis (2007)' },
    { title: 'Dallas Buyers Club (2013)' },
    { title: 'The Pursuit of Happyness (2006)' },
    { title: 'Blood Diamond (2006)' },
    { title: 'The Bourne Ultimatum (2007)' },
    { title: '3-Iron (2004)' },
    { title: 'Sin City (2005)' },
    { title: 'The Diving Bell and the Butterfly (2007)' },
    { title: 'G.O.R.A. (2004)' },
    { title: 'Ratatouille (2007)' },
    { title: 'Casino Royale (2006)' },
    { title: 'Kill Bill: Vol. 2 (2004)' },
    { title: 'The Return (2003)' },
    { title: 'Spring, Summer, Fall, Winter... and Spring (2003)' },
    { title: 'The Sea Inside (I) (2004)' },
    { title: 'Cinderella Man (2005)' },
    { title: 'Kal ho naa ho (2003)' },
    { title: 'Infernal Affairs (2002)' },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    },
    { title: 'Big Fish (2003)' },
    { title: 'The Incredibles (2004)' },
    { title: 'My Sassy Girl (2001)' },
    { title: 'Dogville (2003)' },
    { title: 'Vizontele (2001)' },
    { title: 'Donnie Darko (2001)' },
    { title: 'Monsters, Inc. (2001)' },
    { title: 'Magnolia (1999)' },
    { title: 'Dancer in the Dark (2000)' },
    { title: 'Mulholland Drive (2001)' },
    { title: 'The Straight Story (1999)' },
    { title: 'Perfect Blue (1997)' },
    { title: 'The Celebration (1998)' },
    { title: 'Central Station (1998)' },
    { title: 'The Iron Giant (1999)' },
    { title: "Knockin' on Heaven's Door (1997)" },
    { title: 'Sling Blade (1996)' },
    { title: 'Secrets & Lies (1996)' },
    { title: '12 Monkeys (1995)' },
    { title: 'Ghost in the Shell (1995)' },
    { title: 'The Nightmare Before Christmas (1993)' },
    { title: 'Groundhog Day (1993)' },
    { title: 'Blood In, Blood Out (1993)' },
    { title: 'Scent of a Woman (1992)' },
    { title: 'Aladdin (1992)' },
    { title: 'JFK (1991)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' },
    { title: 'The Bridge on the River Kwai (1957)' },
    { title: 'On the Waterfront (1954)' },
    { title: 'The Wages of Fear (1953)' },
    { title: 'Ace in the Hole (1951)' },
    { title: 'White Heat (1949)' },
    { title: 'The Third Man (1949)' },
    { title: 'The Red Shoes (1948)' },
    { title: 'The Shop Around the Corner (1940)' },
    { title: 'Rebecca (1940)' },
    { title: 'Mr. Smith Goes to Washington (1939)' },
    { title: 'Gone with the Wind (1939)' },
    { title: 'La Grande Illusion (1937)' },
    { title: 'It Happened One Night (1934)' },
    { title: 'The Passion of Joan of Arc (1928)' },
    { title: 'The Circus (1928)' },
    { title: 'Sunrise (1927)' },
    { title: 'The General (1926)' },
    { title: 'The Cabinet of Dr. Caligari (1920)' },
    { title: 'Shoplifters (2018)' },
    { title: 'Badhaai Ho (2018)' },
    { title: 'Marriage Story (2019)' },
    { title: 'Togo (2019)' },
    { title: 'Airlift (2016)' },
    { title: 'Bajrangi Bhaijaan (2015)' },
    { title: 'Baby (I) (2015)' },
    { title: 'La La Land (2016)' },
    { title: 'Lion (2016)' },
    { title: 'The Martian (2015)' },
    { title: 'Zootopia (2016)' },
    { title: 'The Tale of The Princess Kaguya (2013)' },
    { title: 'Wonder (I) (2017)' },
    { title: 'Special 26 (2013)' },
    { title: 'Short Term 12 (2013)' },
    { title: 'The Raid 2 (2014)' },
    { title: 'The Imitation Game (2014)' },
    { title: 'Guardians of the Galaxy (2014)' },
    { title: 'Blade Runner 2049 (2017)' },
    { title: 'Her (2013)' },
    { title: 'Bohemian Rhapsody (2018)' },
    { title: 'The Revenant (2015)' },
    { title: 'The Perks of Being a Wallflower (2012)' },
    { title: 'Elite Squad 2: The Enemy Within (2010)' },
    { title: "The King's Speech (2010)" },
    { title: 'The Help (2011)' },
    { title: 'Deadpool (2016)' },
    { title: 'Darbareye Elly (2009)' },
    { title: 'Dev.D (2009)' },
    { title: 'Ip Man (2008)' },
    { title: 'My Name Is Khan (2010)' },
    { title: 'The Breath (2009)' },
    { title: 'Slumdog Millionaire (2008)' },
    { title: 'Black Swan (2010)' },
    { title: 'The Avengers (2012)' },
    { title: 'Persepolis (2007)' },
    { title: 'Dallas Buyers Club (2013)' },
    { title: 'The Pursuit of Happyness (2006)' },
    { title: 'Blood Diamond (2006)' },
    { title: 'The Bourne Ultimatum (2007)' },
    { title: '3-Iron (2004)' },
    { title: 'Sin City (2005)' },
    { title: 'The Diving Bell and the Butterfly (2007)' },
    { title: 'G.O.R.A. (2004)' },
    { title: 'Ratatouille (2007)' },
    { title: 'Casino Royale (2006)' },
    { title: 'Kill Bill: Vol. 2 (2004)' },
    { title: 'The Return (2003)' },
    { title: 'Spring, Summer, Fall, Winter... and Spring (2003)' },
    { title: 'The Sea Inside (I) (2004)' },
    { title: 'Cinderella Man (2005)' },
    { title: 'Kal ho naa ho (2003)' },
    { title: 'Infernal Affairs (2002)' },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    },
    { title: 'Big Fish (2003)' },
    { title: 'The Incredibles (2004)' },
    { title: 'My Sassy Girl (2001)' },
    { title: 'Dogville (2003)' },
    { title: 'Vizontele (2001)' },
    { title: 'Donnie Darko (2001)' },
    { title: 'Monsters, Inc. (2001)' },
    { title: 'Magnolia (1999)' },
    { title: 'Dancer in the Dark (2000)' },
    { title: 'Mulholland Drive (2001)' },
    { title: 'The Straight Story (1999)' },
    { title: 'Perfect Blue (1997)' },
    { title: 'The Celebration (1998)' },
    { title: 'Central Station (1998)' },
    { title: 'The Iron Giant (1999)' },
    { title: "Knockin' on Heaven's Door (1997)" },
    { title: 'Sling Blade (1996)' },
    { title: 'Secrets & Lies (1996)' },
    { title: '12 Monkeys (1995)' },
    { title: 'Ghost in the Shell (1995)' },
    { title: 'The Nightmare Before Christmas (1993)' },
    { title: 'Groundhog Day (1993)' },
    { title: 'Blood In, Blood Out (1993)' },
    { title: 'Scent of a Woman (1992)' },
    { title: 'Aladdin (1992)' },
    { title: 'JFK (1991)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' },
    { title: 'The Bridge on the River Kwai (1957)' },
    { title: 'On the Waterfront (1954)' },
    { title: 'The Wages of Fear (1953)' },
    { title: 'Ace in the Hole (1951)' },
    { title: 'White Heat (1949)' },
    { title: 'The Third Man (1949)' },
    { title: 'The Red Shoes (1948)' },
    { title: 'The Shop Around the Corner (1940)' },
    { title: 'Rebecca (1940)' },
    { title: 'Mr. Smith Goes to Washington (1939)' },
    { title: 'Gone with the Wind (1939)' },
    { title: 'La Grande Illusion (1937)' },
    { title: 'It Happened One Night (1934)' },
    { title: 'The Passion of Joan of Arc (1928)' },
    { title: 'The Circus (1928)' },
    { title: 'Sunrise (1927)' },
    { title: 'The General (1926)' },
    { title: 'The Cabinet of Dr. Caligari (1920)' },
    { title: 'Shoplifters (2018)' },
    { title: 'Badhaai Ho (2018)' },
    { title: 'Marriage Story (2019)' },
    { title: 'Togo (2019)' },
    { title: 'Airlift (2016)' },
    { title: 'Bajrangi Bhaijaan (2015)' },
    { title: 'Baby (I) (2015)' },
    { title: 'La La Land (2016)' },
    { title: 'Lion (2016)' },
    { title: 'The Martian (2015)' },
    { title: 'Zootopia (2016)' },
    { title: 'The Tale of The Princess Kaguya (2013)' },
    { title: 'Wonder (I) (2017)' },
    { title: 'Special 26 (2013)' },
    { title: 'Short Term 12 (2013)' },
    { title: 'The Raid 2 (2014)' },
    { title: 'The Imitation Game (2014)' },
    { title: 'Guardians of the Galaxy (2014)' },
    { title: 'Blade Runner 2049 (2017)' },
    { title: 'Her (2013)' },
    { title: 'Bohemian Rhapsody (2018)' },
    { title: 'The Revenant (2015)' },
    { title: 'The Perks of Being a Wallflower (2012)' },
    { title: 'Elite Squad 2: The Enemy Within (2010)' },
    { title: "The King's Speech (2010)" },
    { title: 'The Help (2011)' },
    { title: 'Deadpool (2016)' },
    { title: 'Darbareye Elly (2009)' },
    { title: 'Dev.D (2009)' },
    { title: 'Ip Man (2008)' },
    { title: 'My Name Is Khan (2010)' },
    { title: 'The Breath (2009)' },
    { title: 'Slumdog Millionaire (2008)' },
    { title: 'Black Swan (2010)' },
    { title: 'The Avengers (2012)' },
    { title: 'Persepolis (2007)' },
    { title: 'Dallas Buyers Club (2013)' },
    { title: 'The Pursuit of Happyness (2006)' },
    { title: 'Blood Diamond (2006)' },
    { title: 'The Bourne Ultimatum (2007)' },
    { title: '3-Iron (2004)' },
    { title: 'Sin City (2005)' },
    { title: 'The Diving Bell and the Butterfly (2007)' },
    { title: 'G.O.R.A. (2004)' },
    { title: 'Ratatouille (2007)' },
    { title: 'Casino Royale (2006)' },
    { title: 'Kill Bill: Vol. 2 (2004)' },
    { title: 'The Return (2003)' },
    { title: 'Spring, Summer, Fall, Winter... and Spring (2003)' },
    { title: 'The Sea Inside (I) (2004)' },
    { title: 'Cinderella Man (2005)' },
    { title: 'Kal ho naa ho (2003)' },
    { title: 'Infernal Affairs (2002)' },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    },
    { title: 'Big Fish (2003)' },
    { title: 'The Incredibles (2004)' },
    { title: 'My Sassy Girl (2001)' },
    { title: 'Dogville (2003)' },
    { title: 'Vizontele (2001)' },
    { title: 'Donnie Darko (2001)' },
    { title: 'Monsters, Inc. (2001)' },
    { title: 'Magnolia (1999)' },
    { title: 'Dancer in the Dark (2000)' },
    { title: 'Mulholland Drive (2001)' },
    { title: 'The Straight Story (1999)' },
    { title: 'Perfect Blue (1997)' },
    { title: 'The Celebration (1998)' },
    { title: 'Central Station (1998)' },
    { title: 'The Iron Giant (1999)' },
    { title: "Knockin' on Heaven's Door (1997)" },
    { title: 'Sling Blade (1996)' },
    { title: 'Secrets & Lies (1996)' },
    { title: '12 Monkeys (1995)' },
    { title: 'Ghost in the Shell (1995)' },
    { title: 'The Nightmare Before Christmas (1993)' },
    { title: 'Groundhog Day (1993)' },
    { title: 'Blood In, Blood Out (1993)' },
    { title: 'Scent of a Woman (1992)' },
    { title: 'Aladdin (1992)' },
    { title: 'JFK (1991)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' },
    { title: 'The Bridge on the River Kwai (1957)' },
    { title: 'On the Waterfront (1954)' },
    { title: 'The Wages of Fear (1953)' },
    { title: 'Ace in the Hole (1951)' },
    { title: 'White Heat (1949)' },
    { title: 'The Third Man (1949)' },
    { title: 'The Red Shoes (1948)' },
    { title: 'The Shop Around the Corner (1940)' },
    { title: 'Rebecca (1940)' },
    { title: 'Mr. Smith Goes to Washington (1939)' },
    { title: 'Gone with the Wind (1939)' },
    { title: 'La Grande Illusion (1937)' },
    { title: 'It Happened One Night (1934)' },
    { title: 'The Passion of Joan of Arc (1928)' },
    { title: 'The Circus (1928)' },
    { title: 'Sunrise (1927)' },
    { title: 'The General (1926)' },
    { title: 'The Cabinet of Dr. Caligari (1920)' },
    { title: 'Shoplifters (2018)' },
    { title: 'Badhaai Ho (2018)' },
    { title: 'Marriage Story (2019)' },
    { title: 'Togo (2019)' },
    { title: 'Airlift (2016)' },
    { title: 'Bajrangi Bhaijaan (2015)' },
    { title: 'Baby (I) (2015)' },
    { title: 'La La Land (2016)' },
    { title: 'Lion (2016)' },
    { title: 'The Martian (2015)' },
    { title: 'Zootopia (2016)' },
    { title: 'The Tale of The Princess Kaguya (2013)' },
    { title: 'Wonder (I) (2017)' },
    { title: 'Special 26 (2013)' },
    { title: 'Short Term 12 (2013)' },
    { title: 'The Raid 2 (2014)' },
    { title: 'The Imitation Game (2014)' },
    { title: 'Guardians of the Galaxy (2014)' },
    { title: 'Blade Runner 2049 (2017)' },
    { title: 'Her (2013)' },
    { title: 'Bohemian Rhapsody (2018)' },
    { title: 'The Revenant (2015)' },
    { title: 'The Perks of Being a Wallflower (2012)' },
    { title: 'Elite Squad 2: The Enemy Within (2010)' },
    { title: "The King's Speech (2010)" },
    { title: 'The Help (2011)' },
    { title: 'Deadpool (2016)' },
    { title: 'Darbareye Elly (2009)' },
    { title: 'Dev.D (2009)' },
    { title: 'Ip Man (2008)' },
    { title: 'My Name Is Khan (2010)' },
    { title: 'The Breath (2009)' },
    { title: 'Slumdog Millionaire (2008)' },
    { title: 'Black Swan (2010)' },
    { title: 'The Avengers (2012)' },
    { title: 'Persepolis (2007)' },
    { title: 'Dallas Buyers Club (2013)' },
    { title: 'The Pursuit of Happyness (2006)' },
    { title: 'Blood Diamond (2006)' },
    { title: 'The Bourne Ultimatum (2007)' },
    { title: '3-Iron (2004)' },
    { title: 'Sin City (2005)' },
    { title: 'The Diving Bell and the Butterfly (2007)' },
    { title: 'G.O.R.A. (2004)' },
    { title: 'Ratatouille (2007)' },
    { title: 'Casino Royale (2006)' },
    { title: 'Kill Bill: Vol. 2 (2004)' },
    { title: 'The Return (2003)' },
    { title: 'Spring, Summer, Fall, Winter... and Spring (2003)' },
    { title: 'The Sea Inside (I) (2004)' },
    { title: 'Cinderella Man (2005)' },
    { title: 'Kal ho naa ho (2003)' },
    { title: 'Infernal Affairs (2002)' },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    },
    { title: 'Big Fish (2003)' },
    { title: 'The Incredibles (2004)' },
    { title: 'My Sassy Girl (2001)' },
    { title: 'Dogville (2003)' },
    { title: 'Vizontele (2001)' },
    { title: 'Donnie Darko (2001)' },
    { title: 'Monsters, Inc. (2001)' },
    { title: 'Magnolia (1999)' },
    { title: 'Dancer in the Dark (2000)' },
    { title: 'Mulholland Drive (2001)' },
    { title: 'The Straight Story (1999)' },
    { title: 'Perfect Blue (1997)' },
    { title: 'The Celebration (1998)' },
    { title: 'Central Station (1998)' },
    { title: 'The Iron Giant (1999)' },
    { title: "Knockin' on Heaven's Door (1997)" },
    { title: 'Sling Blade (1996)' },
    { title: 'Secrets & Lies (1996)' },
    { title: '12 Monkeys (1995)' },
    { title: 'Ghost in the Shell (1995)' },
    { title: 'The Nightmare Before Christmas (1993)' },
    { title: 'Groundhog Day (1993)' },
    { title: 'Blood In, Blood Out (1993)' },
    { title: 'Scent of a Woman (1992)' },
    { title: 'Aladdin (1992)' },
    { title: 'JFK (1991)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' },
    { title: 'The Bridge on the River Kwai (1957)' },
    { title: 'On the Waterfront (1954)' },
    { title: 'The Wages of Fear (1953)' },
    { title: 'Ace in the Hole (1951)' },
    { title: 'White Heat (1949)' },
    { title: 'The Third Man (1949)' },
    { title: 'The Red Shoes (1948)' },
    { title: 'The Shop Around the Corner (1940)' },
    { title: 'Rebecca (1940)' },
    { title: 'Mr. Smith Goes to Washington (1939)' },
    { title: 'Gone with the Wind (1939)' },
    { title: 'La Grande Illusion (1937)' },
    { title: 'It Happened One Night (1934)' },
    { title: 'The Passion of Joan of Arc (1928)' },
    { title: 'The Circus (1928)' },
    { title: 'Sunrise (1927)' },
    { title: 'The General (1926)' },
    { title: 'The Cabinet of Dr. Caligari (1920)' },
    { title: 'Shoplifters (2018)' },
    { title: 'Badhaai Ho (2018)' },
    { title: 'Marriage Story (2019)' },
    { title: 'Togo (2019)' },
    { title: 'Airlift (2016)' },
    { title: 'Bajrangi Bhaijaan (2015)' },
    { title: 'Baby (I) (2015)' },
    { title: 'La La Land (2016)' },
    { title: 'Lion (2016)' },
    { title: 'The Martian (2015)' },
    { title: 'Zootopia (2016)' },
    { title: 'The Tale of The Princess Kaguya (2013)' },
    { title: 'Wonder (I) (2017)' },
    { title: 'Special 26 (2013)' },
    { title: 'Short Term 12 (2013)' },
    { title: 'The Raid 2 (2014)' },
    { title: 'The Imitation Game (2014)' },
    { title: 'Guardians of the Galaxy (2014)' },
    { title: 'Blade Runner 2049 (2017)' },
    { title: 'Her (2013)' },
    { title: 'Bohemian Rhapsody (2018)' },
    { title: 'The Revenant (2015)' },
    { title: 'The Perks of Being a Wallflower (2012)' },
    { title: 'Elite Squad 2: The Enemy Within (2010)' },
    { title: "The King's Speech (2010)" },
    { title: 'The Help (2011)' },
    { title: 'Deadpool (2016)' },
    { title: 'Darbareye Elly (2009)' },
    { title: 'Dev.D (2009)' },
    { title: 'Ip Man (2008)' },
    { title: 'My Name Is Khan (2010)' },
    { title: 'The Breath (2009)' },
    { title: 'Slumdog Millionaire (2008)' },
    { title: 'Black Swan (2010)' },
    { title: 'The Avengers (2012)' },
    { title: 'Persepolis (2007)' },
    { title: 'Dallas Buyers Club (2013)' },
    { title: 'The Pursuit of Happyness (2006)' },
    { title: 'Blood Diamond (2006)' },
    { title: 'The Bourne Ultimatum (2007)' },
    { title: '3-Iron (2004)' },
    { title: 'Sin City (2005)' },
    { title: 'The Diving Bell and the Butterfly (2007)' },
    { title: 'G.O.R.A. (2004)' },
    { title: 'Ratatouille (2007)' },
    { title: 'Casino Royale (2006)' },
    { title: 'Kill Bill: Vol. 2 (2004)' },
    { title: 'The Return (2003)' },
    { title: 'Spring, Summer, Fall, Winter... and Spring (2003)' },
    { title: 'The Sea Inside (I) (2004)' },
    { title: 'Cinderella Man (2005)' },
    { title: 'Kal ho naa ho (2003)' },
    { title: 'Infernal Affairs (2002)' },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    },
    { title: 'Big Fish (2003)' },
    { title: 'The Incredibles (2004)' },
    { title: 'My Sassy Girl (2001)' },
    { title: 'Dogville (2003)' },
    { title: 'Vizontele (2001)' },
    { title: 'Donnie Darko (2001)' },
    { title: 'Monsters, Inc. (2001)' },
    { title: 'Magnolia (1999)' },
    { title: 'Dancer in the Dark (2000)' },
    { title: 'Mulholland Drive (2001)' },
    { title: 'The Straight Story (1999)' },
    { title: 'Perfect Blue (1997)' },
    { title: 'The Celebration (1998)' },
    { title: 'Central Station (1998)' },
    { title: 'The Iron Giant (1999)' },
    { title: "Knockin' on Heaven's Door (1997)" },
    { title: 'Sling Blade (1996)' },
    { title: 'Secrets & Lies (1996)' },
    { title: '12 Monkeys (1995)' },
    { title: 'Ghost in the Shell (1995)' },
    { title: 'The Nightmare Before Christmas (1993)' },
    { title: 'Groundhog Day (1993)' },
    { title: 'Blood In, Blood Out (1993)' },
    { title: 'Scent of a Woman (1992)' },
    { title: 'Aladdin (1992)' },
    { title: 'JFK (1991)' },
    { title: 'Nights of Cabiria (1957)' },
    { title: 'Throne of Blood (1957)' }
  ];

  module.exports = movieData;